### ISSUE TITLE
Config Get/Set/List Commands

### ISSUE THREAD

**Issue by Hbbb** [Freshly/tuber#54]
Is there any other configuration that an app would need to read/write to besides env vars? If not, we can drop the `env` argument in the below command suggestions. 

`tubectl config set env NAME=VALUE`
`tubectl config get env NAME`
`tubectl config list env`

Debating on the fact that people even need to know that configs are stored as Kubernetes secrets as opposed to plain config maps. It seems reasonable to group all of these commands under the name `config`.

**Comment by jkminneti** [comment]
It's now `env set`, `env unset`, `env get`, can we close this?

**Comment by quinn** [comment]
done
