### ISSUE TITLE
Custom secrets and configmaps

### ISSUE THREAD

**Issue by jkminneti** [Freshly/tuber#83]
Right now, an end user can control anything about their namespace through `.tuber`'s. Custom resources, extra resources, whatever. Except for secrets and configmaps.

Secrets and configmaps and their data shouldn't be committed to code, but we should be able to tear down and recreate a tuberapp entirely from 1 - the resources tuber creates, and 2 - the resources in `.tuber`.

How do we do this? Not sure.

**Comment by quinn** [comment]
```
$ tuber secrets
usage: secrets create [name] [folder or file]
       secrets delete [name]
$ tuber secrets -a app certs ./certs
```

Everything else is handled by `tuber env`

**Comment by quinn** [comment]
the equivalent kubectl would be:

```
$ kubectl create secret generic certs --from-file=./certs/domain.key --from-file=./certs/domain.cert
```

**Comment by jkminneti** [comment]
But then it's not represented in code is all

**Comment by quinn** [comment]
neither are env vars.
